### ISSUE TITLE
contact information is incorrect

### ISSUE THREAD

**Issue by jlcohoon** [cos-archives/archival-project#13]
On the contact page (http://archivalproject.org/pages/contact), Roger's name is spelled incorrectly and links to the wrong email address. 
It should read "Roger Giner-Sorrolla" and link to "r.s.giner-sorolla@kent.ac.uk"

**Comment by RogerGiner-Sorolla** [comment]
Well, Roger Giner-Sorolla with one r that is.

**Comment by jlcohoon** [comment]
typos everywhere
